spring:
  datasource:
    url: jdbc:mysql://localhost:3307/pm?useUnicode=true&allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=utf-8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

jwt:
  secret: Lorde